targets:
  - name: "Test Server"
    ip: "127.0.0.1"
    cron: "* * * * *"
    ports:
      - port: 8000
        strategy: port
        notify:
          - via: telegram
            chat: tibebe
            from: bot
            errorTemplate: ""
            successTemplate: ""
          - via: email
            email: tibebe@gmail.com
            from: bot
            errorTemplate: ""
            successTemplate: ""
    errorTemplate: ""
    successTemplate: ""
    rules:
      - failed: ">3"
        notify:
        - via: telegram
          chat: tibebe
          from: bot
          errorTemplate: ""
          successTemplate: ""
        - via: email
          email: tibebe@gmail.com
          from: bot
          errorTemplate: ""
          successTemplate: ""
notifications:
  telegram:
    bots:
      - name: "bot"
        token: "123456:bottoken"
    chats:
      - name: "tibebe"
        chatid: -123456789
      - name: "tibebe"
        chatid: -123456789
  webhook:
    - name: "webhook api"
      endpoint: "http://localhost:8000"
      auth:
        endpoint: "http://localhost:7000"
        email: "test@gmail.com"
        password: "password"
