targets:
  - name: "Test Server"
    ip: "127.0.0.1"
    cron: "*/5 * * * *"
    strategy: status-code
    https: false
    ports:
      - port: 8000
        notify:
          - via: telegram
            chat: go-alive-test-group
            from: go-alive-test-bot
            template: ""
      - port: 8010
        notify:
    rules:
      - failures: ">0"
        notify:
        - via: telegram
          chat: go-alive-test-group
          from: go-alive-test-bot
          template: >
            IP: {{.Host}}

            Scan Type: {{.Strategy}}


            Scan summary:
            {{range .Results}}
              port: {{.Port}}
              reachable: {{.IsReachable}}
                ------------{{end}}
        - via: telegram
          chat: go-alive-test-group
          from: go-alive-test-bot
          template: >
            IP: {{.Host}}

            Scan Type: {{.Strategy}}


            Scan summary:
            {{range .Results}}
              port: {{.Port}}
              reachable: {{.IsReachable}}
                ------------{{end}}
        - via: slack
          channel: go-alive-test-group
          from: go-alive-test-bot
          template: >
            IP: {{.Host}}

            Scan Type: {{.Strategy}}

            Scan summary:
            {{range .Results}}
              port: {{.Port}}
              reachable: {{.IsReachable}}
              {{ if .Error }}
                error:
                  {{ .Error }}
              {{end}}
                ------------
            {{end}}
        - via: email
          from: "tibebe"
          to: test@gmail.com
          subject: "Go-Alive Test Report"
          template: >
            IP: {{.Host}}

            Scan Type: {{.Strategy}}

            Scan summary:
            {{range .Results}}
              port: {{.Port}}
              reachable: {{.IsReachable}}
              {{ if .Error }}
                error:
                  {{ .Error }}
              {{end}}
                ------------
            {{end}}
notifications:
  telegram:
    bots:
      - name: "go-alive-test-bot"
        token: "123456:bot-token"
    chats:
      - name: "go-alive-test-group"
        chatid: 1123232322
      - name: "tibebe"
        chatid: 12345678
  email:
    smtp:
      - name: "tibebe"
        sender: "test@gmail.com"
        auth:
          username: "test@gmail.com"
          password: "password"
        server: "smtp.gmail.com"
        port: 587
  slack:
    apps:
      - name: "go-alive-test-bot"
        token: "bot user token"
    channels:
      - name: "go-alive-test-group"
        channelid: 'channel id'
  webhook:
    - name: "webhook api"
      endpoint: "http://localhost:8000"
      auth:
        endpoint: "http://localhost:7000"
        email: "test@gmail.com"
        password: "password"
